# Generated by Django 4.2 on 2026-04-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_input', models.JSONField()),
                ('predicted_segment', models.CharField(max_length=50)),
                ('probability_scores', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('conversation_type', models.CharField(choices=[('consultation', 'Tư vấn sản phẩm'), ('product_info', 'Thông tin sản phẩm'), ('policy', 'Chính sách'), ('complaint', 'Khiếu nại')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchases', models.IntegerField(default=0)),
                ('avg_spending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preferred_device_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('both', 'Cả hai')], default='both', max_length=20)),
                ('preferred_budget_range', models.CharField(choices=[('low', 'Dưới 10 triệu'), ('mid', '10-20 triệu'), ('high', '20-30 triệu'), ('premium', 'Trên 30 triệu')], default='mid', max_length=20)),
                ('avg_session_duration', models.IntegerField(default=0, help_text='Tính bằng phút')),
                ('product_view_count', models.IntegerField(default=0)),
                ('favorite_categories', models.JSONField(blank=True, default=dict)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('loyalty_score', models.FloatField(default=0.0, help_text='0-1.0')),
                ('churn_risk', models.FloatField(default=0.0, help_text='0-1.0, cao = nguy hiểm mất khách')),
                ('predicted_segment', models.CharField(blank=True, help_text="VD: 'High-Value', 'At-Risk', 'New'", max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Behaviors',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('product', 'Thông tin sản phẩm'), ('guide', 'Hướng dẫn sử dụng'), ('policy', 'Chính sách & qui định'), ('technical', 'Thông số kỹ thuật'), ('comparison', 'So sánh sản phẩm')], max_length=20)),
                ('related_products', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags để tìm kiếm')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector nhúng để RAG retrieval', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Advisor')], max_length=20)),
                ('content', models.TextField()),
                ('context_sources', models.JSONField(blank=True, default=list, help_text='Danh sách KB sources được dùng để trả lời')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisor.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['content_type', 'is_active'], name='advisor_kno_content_3f8f6b_idx'),
        ),
        migrations.AddField(
            model_name='customerbehavior',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='behavioranalysislog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='advisor_mes_session_ff8dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['session_id'], name='advisor_con_session_f09dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', 'created_at'], name='advisor_con_user_id_c64125_idx'),
        ),
    ]
